AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  placesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${StackTagName} Environment ${EnvironmentTagName}
        - ResourceName: placesApi
      StageName: !Ref EnvironmentAPIGatewayStageName
      DefinitionBody:
        swagger: '2.0'
        info: {}
        paths:
          /places:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getPlaces.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${addPlace.Arn}/invocations
              responses: {}
          /places/{id}:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${editPlace.Arn}/invocations
              responses: {}
          /places/{id}/hours:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${editHours.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors: '''*'''
  getPlaces:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-getPlaces
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: getPlaces
      CodeUri: src/get-places
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref placeHours
        - DynamoDBCrudPolicy:
            TableName: !Ref places
      Events:
        placesApiGETplaces:
          Type: Api
          Properties:
            Path: /places
            Method: GET
            RestApiId: !Ref placesApi
      Environment:
        Variables:
          PLACE_HOURS_TABLE_NAME: !Ref placeHours
          PLACE_HOURS_TABLE_ARN: !GetAtt placeHours.Arn
          PLACES_TABLE_NAME: !Ref places
          PLACES_TABLE_ARN: !GetAtt places.Arn
  places:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: place_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: place_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-places
  placeHours:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: place_id
          AttributeType: S
        - AttributeName: day_hours
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: place_id
          KeyType: HASH
        - AttributeName: day_hours
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-placeHours
  addPlace:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-addPlace
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: addPlace
      CodeUri: src/add-place
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref placeHours
        - DynamoDBCrudPolicy:
            TableName: !Ref places
      Events:
        placesApiPOSTplaces:
          Type: Api
          Properties:
            Path: /places
            Method: POST
            RestApiId: !Ref placesApi
      Environment:
        Variables:
          PLACES_TABLE_NAME: !Ref places
          PLACES_TABLE_ARN: !GetAtt places.Arn
  editPlace:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-editPlace
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: editPlace
      CodeUri: src/edit-place
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref places
        - DynamoDBCrudPolicy:
            TableName: !Ref placeHours
      Events:
        placesApiPUTplacesid:
          Type: Api
          Properties:
            Path: /places/{id}
            Method: PUT
            RestApiId: !Ref placesApi
      Environment:
        Variables:
          PLACE_HOURS_TABLE_NAME: !Ref placeHours
          PLACE_HOURS_TABLE_ARN: !GetAtt placeHours.Arn
          PLACES_TABLE_NAME: !Ref places
          PLACES_TABLE_ARN: !GetAtt places.Arn
  editHours:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-editHours
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: editHours
      CodeUri: src/edit-hours
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref placeHours
        - DynamoDBCrudPolicy:
            TableName: !Ref places
      Events:
        placesApiPUTplacesidhours:
          Type: Api
          Properties:
            Path: /places/{id}/hours
            Method: PUT
            RestApiId: !Ref placesApi
      Environment:
        Variables:
          TABLE_NAME: !Ref placeHours
          TABLE_ARN: !GetAtt placeHours.Arn
          TABLE_NAME_2: !Ref places
          TABLE_ARN_2: !GetAtt places.Arn
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (injected by Stackery at deployment time)